#server
server:
  port: 80
  servlet:
    context-path: /
#spring
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///yonghedb?serverTimezone=GMT%2B8&characterEncoding=UTF8
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: priv.zg.pojo
  configuration:
    map-underscore-to-camel-case: true